---

- name: "LAMP & Wordpress Installation"
  become: true
  hosts: all
  roles:
    - LAMP

  tasks:

    - name: "Download wordpress archive file"
      get_url:
            url: "{{ wp_url }}"
            dest: /tmp/wordpress.tar.gz
       

    - name: "Unarchiving wordpress.tar.gz"
      unarchive:
             src: /tmp/wordpress.tar.gz
             dest: /tmp/
             remote_src: true

    - name: "Copying contents"
      copy:
             src: /tmp/wordpress/
             dest: "{{ doc_root }}/{{ domain_name }}/"
             remote_src: true
             owner: "{{ httpd_user }}"
             group: "{{ httpd_group }}"
     

    - name: "Creating wp-config.php"
      template:
              src: wp-config.php.tmpl
              dest: "{{ doc_root }}/{{ domain_name }}/"
              owner: "{{ httpd_user }}"
              group: "{{ httpd_group }}"
    

    - name: "Cleaning up installation files"
      file:
            path: "{{ item }}"
            state: absent
      with_items:

            - /tmp/wordpress
            - /tmp/wordpress.tar.gz
            
            

