---
#httpd installation
- name: "Webserver Package Installation for linux"
  yum:
    name: httpd
    state: present
  notify:
    - Restarting-enabling-httpd
#php installation
- name: "PHP Package Installation"
  shell: amazon-linux-extras install php7.4 -y
- name: "Create httpd conf template"
  template:
   src: httpd.conf.tmpl
   dest: /etc/httpd/conf/httpd.conf
  notify:
   - Restarting-enabling-httpd
#add vhost template
- name: "Create vhost from template"
  template:
   src: vhost.conf.tmpl
   dest: "/etc/httpd/conf.d/{{ domain_name }}.conf"
  notify:
   - Restarting-enabling-httpd
# create Document root
- name: "Create documentroot"
  file:
   path: "{{ doc_root }}/{{ domain_name }}/"
   state: directory
   owner: "{{ httpd_user }}"
   group: "{{ httpd_group }}"
#add default page of php
- name: "Create test.php and test.html"
  copy:
    src: "{{ item }}"
    dest: "{{ doc_root }}/{{ domain_name }}/"
    owner: "{{ httpd_user }}"
    group: "{{ httpd_group }}"
  with_items:
    - test.php
    - test.html
#Installing the database
- name: Install firewalld
  yum: 
    name: firewalld
    state: present

- name: Start firewalld
  service: 
    name: firewalld
    state: started

- name: Enable the Service
  systemd:
    name: firewalld
    enabled: yes 

- name: Deploy and Configure Database
  yum: 
    name: mariadb-server
    state: present
  
- name: Start Database
  service: 
    name: mariadb
    state: started

- name: Enable Database
  systemd:
    name: mariadb
    enabled: yes

- name: Configuring firewall for Database
  firewalld:
    port: 3306/tcp
    zone: public
    permanent: yes
    immediate: yes
    state: enabled

- name: Make sure pymysql is present
  pip:
    name: pymysql
    state: present

- name: Install mysql
  yum:
    name: MySQL-python
    state: latest
