---

- import_tasks: amazon.yml
  when: ansible_os_family == "RedHat" and ansible_distribution == "Amazon"

- import_tasks: centos.yml
  when: ansible_os_family == "RedHat" and ansible_distribution == "CentOS"

- name: "Create httpd conf template"
  template:
   src: httpd.conf.tmpl
   dest: /etc/httpd/conf/httpd.conf
  notify:
   - Restarting-enabling-httpd

- name: "Create vhost from template"
  template:
   src: vhost.conf.tmpl
   dest: "/etc/httpd/conf.d/{{ domain_name }}.conf"
  notify:
   - Restarting-enabling-httpd

- name: "Create documentroot"
  file:
   path: "{{ doc_root }}/{{ domain_name }}/"
   state: directory
   owner: "{{ httpd_user }}"
   group: "{{ httpd_group }}"

- name: "Create test.php and test.html"
  copy:
    src: "{{ item }}"
    dest: "{{ doc_root }}/{{ domain_name }}/"
    owner: "{{ httpd_user }}"
    group: "{{ httpd_group }}"
  with_items:
    - test.php
    - test.html

- name: "Install mariadb package"
  yum:
   name:
    - mariadb-server
    - MySQL-python
   state: present

- name: "Restarting/enabling mariadb"
  service:
   name: mariadb
   state: restarted
   enabled: true

- name: "Mariadb root password set"
  ignore_errors: true
  mysql_user:
   login_user: "root"
   login_password: ""
   user: "root"
   password: "{{ mdb_root_pass }}"
   host_all: true


- name: "Removing anonymous users"
  mysql_user:
   login_user: "root"
   login_password: "{{ mdb_root_pass }}"
   user: ""
   state: absent
   host_all: true


- name: "Removing test database"
  mysql_db:
   login_user: "root"
   login_password: "{{ mdb_root_pass }}"
   name: "test"
   state: absent

- name: "Creating database"
  mysql_db:
   login_user: "root"
   login_password: "{{ mdb_root_pass }}"
   name: "{{ mdb_db }}"
   state: present

- name: "Creating dbuser & dbpassword"
  mysql_user:
    login_user: "root"
    login_password: "{{ mdb_root_pass }}"
    name: "{{ mdb_user }}"
    password: "{{ mdb_pw }}"
    host: "%"
