---
#include amazon_linx file and ubntu file
- include_tasks: amazon_linux.yml
  when: ansible_os_family == "RedHat"
- include_tasks: ubuntu.yml
  when: ansible_os_family == "Debian"
    #include variable files for ubuntu and linux
- name: Include Ubuntu variables.
  include_vars: ubuntu_var.yml
- name: Include linux variables.
  include_vars: main.yml
