##################################################
# DO Community Playbooks: LAMP on Ubuntu 18.04
##################################################
---
# install all prereqisites
    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]
#install all Lamp packages
  #Apache Configuration
    - name: Install LAMP Packages
      apt: name={{ item }} update_cache=yes state=absent
      loop: [ 'apache2', 'mysql-server', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php', 'perl' ]
      notify:
         - Restart mysql
#start and enable mysql service
    - name: start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: yes
#creating mysql user and database
    - name: creating mysql user
      mysql_user:
        name: "{{db_user}}"
        password: "{{db_pass}}"
        priv: '*.*:ALL,GRANT'
        host: localhost
        state: present
    - name: creating database
      mysql_db:
        name: "{{db_name}}"
        state: present
#enable root login to user
    - name: Enable remote login to mysql
      lineinfile:
         path: /etc/mysql/mysql.conf.d/mysqld.cnf
         regexp: '^bind-address'
         line: 'bind-address = 0.0.0.0'
         backup: yes
      notify:
         - Restart mysql
    - name: Sets the root password
      mysql_user:
        name: root
        password: "{{ db_pass }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
# Create Document root
    - name: Create document root
      file:
        path: "/var/www/html"
        state: directory
        owner: root
        mode: '0755'

    - name: Set up Apache virtualhost
      template:
        src: apache.conf.j2
        dest: "/etc/apache2/sites-available/"
      notify: Reload Apache

    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

# PHP Info Page
    - name: Sets Up PHP Info Page
      template:
        src: info.php.j2
        dest: "/var/www/html/info.php"
      notify:
          - Reload Apache
          - Restart Apache

